name: rsumitradelima
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  line_awesome_icons: ^1.0.4+2
  google_nav_bar: ^2.2.0
  flutter_svg: any
  url_launcher: ^5.5.0
  font_awesome_flutter: ^8.5.0
  line_icons: ^0.2.0
  flutter_icons: ^1.0.0+1
  http: ^0.12.0+4
  webview_flutter: ^0.3.22+1
  splashscreen:
  photo_view: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/rsmd_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/app_logo.png
    - assets/timeline.png
    - assets/fitur_komplain.png
    - assets/header.png
    - assets/home/
    - assets/jadwaldokter/
    - assets/jadwaldokter/kandungan.png
    - assets/jadwaldokter/mata.png
    - assets/jadwaldokter/bedah.png
    - assets/jadwaldokter/syaraf.png
    - assets/jadwaldokter/anak.png
    - assets/jadwaldokter/gigi.png
    - assets/jadwaldokter/bedahplastik.png
    - assets/jadwaldokter/dalam.png
    - assets/jadwaldokter/rehab.png
    - assets/jadwaldokter/ortho.png
    - assets/jadwaldokter/paru.png
    - assets/jadwaldokter/urologi.png
    - assets/jadwaldokter/tht.png
    - assets/jadwaldokter/jiwa.png
    - assets/dokter/andi.png
    - assets/dokter/ade.png
    - assets/dokter/niluh.png
    - assets/dokter/dewi.png
    - assets/dokter/widiyanti.png
    - assets/dokter/widi.png
    - assets/dokter/user.png
    - assets/dokter/luky.png
    - assets/dokter/tutik.png
    - assets/dokter/rahmad.png
    - assets/dokter/muji.png
    - assets/dokter/faris.png
    - assets/dokter/eka.png
    - assets/dokter/aan.png
    - assets/dokter/lukman.png
    - assets/dokter/sastia.png
    - assets/dokter/garin.png
    - assets/dokter/medi.png
    - assets/dokter/inneke.png
    - assets/dokter/maya.png
    - assets/dokter/vivi.png
    - assets/dokter/deddy.png
    - assets/dokter/vivi.png
    - assets/dokter/vivi.png
    - assets/dokter/vivi.png
    - assets/dokter/vivi.png
    - assets/dokter/vivi.png
    - assets/dokter/vivi.png
    - assets/kontak/map.png
    - assets/kontak/pin.png
    - assets/kontak/information.png
    - assets/kontak/call.png
    - assets/kontak/ambulance.png
    - assets/kontak/email.png
    - assets/kontak/email2.png
    - assets/kontak/ig.png
    - assets/kontak/ig1.png
    - assets/kontak/fb.png
    - assets/kontak/fb1.png
    - assets/kontak/web.png
    - assets/kontak/web1.png
    - assets/berita/igd.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BauhausReguler
      fonts:
        - asset: assets/fonts/Bauhaus.ttf
    - family: Emirates
      fonts:
        - asset: assets/fonts/Emirates.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
